# Generated by Django 4.2.7 on 2025-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocular", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocularimage",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional notes about the image", null=True
            ),
        ),
    ]
